#!/bin/sh

# rootかの確認
if [ $(id -u) -ne 0 ]; then
    echo "This script must be run as root." >&2
    exit 1
fi

case "$1" in
    stop)
        while [ "$(cat /tmp/autoswap_busy)" -ne "0" ]; do sleep 0.9; done; kill -TERM $2; exit 0 ;;
    reload)
        while [ "$(cat /tmp/autoswap_busy)" -ne "0" ]; do sleep 0.9; done; kill -HUP $2; exit 0 ;;
    esac

# 設定ファイルより変数を読み込み
. /usr/local/etc/autoswap.conf || { echo "Failed to load configuration file" >&2; exit 1; }

# 数字かどうかを判定
isnum() {
    case ${1#[+-]} in
        *[!0-9]*) return 1 ;;
        *) return 0 ;;
    esac
}

# ディレクトリの作成とスワップファイルの番号の初期化など
num=0

if [ -e /usr/local/share/autoswap ]; then
    for file in /usr/local/share/autoswap/*; do
        if isnum "${file##*/}"; then
            num=$((num + 1))
        fi
    done
else
    mkdir /usr/local/share/autoswap
fi

# busyかわかるように
echo "0" > /tmp/autoswap_busy

while true; do
    # busy
    echo "1" > /tmp/autoswap_busy

    # 空きメモリの取得
    free=$(free | awk '{ if ( NR % 4 == 3 ) { print int( $4 / 1024 ) } }')

    if [ ${free} -lt ${WHEN_TO_SWAP} ]; then
        # スワップファイルの作成と有効化
        mkswap -U clear --size ${SWAP_FILE_SIZE}M --file /usr/local/share/autoswap/${num} > /dev/null || echo "Failed to create swap file" >&2
        swapon /usr/local/share/autoswap/${num}  > /dev/null || echo "Failed to enable swap file" >&2

        echo "Added swap file: /usr/local/share/autoswap/${num}"

        # 足し算
        num=$((num + 1))

    elif [ ${free} -gt ${WHEN_TO_UNSWAP} ] && [ ${num} -gt 0 ]; then
        # スワップファイルの無効化と削除
        swapoff /usr/local/share/autoswap/$((num - 1)) > /dev/null || echo "Failed to disable swap file" >&2
        rm /usr/local/share/autoswap/$((num - 1)) > /dev/null || echo "Failed to remove swap file" >&2

        echo "Removed swap file: /usr/local/share/autoswap/$((num - 1))"

        # 引き算
        num=$((num - 1))
    fi

    # unbusy
    echo "0" > /tmp/autoswap_busy

    # ちゃんと待とうね
    sleep 1
done
